### ISSUE TITLE
Not able to give TFTP protocol and URL in Upload Repository field 

### ISSUE THREAD

**Issue by karthika-ab** [rdkcentral/xconfserver#25]
We are not able to add TFTP protocol and corresponding URL in the Upload repository field  under DCM.The following exception is thrown : 

![tftp](https://user-images.githubusercontent.com/77378613/105285170-ddac0080-5bd9-11eb-934a-2f3abaf4cb9b.png)

It is seen that the issue is not observed in the case of HTTP and HTTPS protocols.

**Comment by ajayan508** [comment]
The same issue exists for  telemetry profile settings also.

If we give IP address in the URL field, instead of a valid URL for 'tftp' option, this error is getting displayed. But for http protocol, we can save URL in the  form of IP address only.

![image](https://user-images.githubusercontent.com/49313548/107952650-0c8e7a00-6fc0-11eb-9ad9-fbdab2bd32ee.png)

**Comment by gdj-cmcst** [comment]
The first part of the issue was addressed with this commit:

https://github.com/rdkcentral/xconfserver/commit/009eb30ebd98c6f7f8cdcae4636ec12bbe1b7681

This new amendment to the issue will need to be looked into.

**Comment by igor-kostrov** [comment]
The commit 009eb30 fixes issue in Telemtry Profile as well.

**Comment by ajayan508** [comment]
Verified in the new build and the issue doesn't exist in the new build.
